public class MonthConversion {
    public static String convertMonthIntegerToString(Integer matrixMonth){
    if(matrixMonth == 1){
        return 'January';   
    }else if(matrixMonth == 2){
        return 'February';   
    }else if(matrixMonth == 3){
        return 'March';   
    }else if(matrixMonth == 4){
        return 'April';   
    }else if(matrixMonth == 5){
        return 'May';       
    }else if(matrixMonth == 6){            
        return 'June';   
    }else if(matrixMonth == 7){
        return 'July';   
    }else if(matrixMonth ==8){
        return 'August';   
    }else if(matrixMonth == 9){
        return 'September';   
    }else if(matrixMonth == 10){
        return 'October';  
    }else if(matrixMonth == 11 ){
        return 'November';  
    }else{
        return 'December';
    }
}

}